quarkus.application.name=weather-aggregator-${HOSTNAME:1}
quarkus.http.port=9080

# Redis Configuration
quarkus.redis.health.enabled=true

# Logging
quarkus.log.category."org.acme".level=${LOG_LEVEL:INFO}
%dev.quarkus.log.category."org.acme".level=DEBUG

# redis dev-services configuration (I am using specific port for Native IntegrationTests)
quarkus.redis.devservices.enabled=true
quarkus.redis.devservices.port=6379
quarkus.http.test-port=8888