pipeline {
    agent any
    stages {
        stage('Executar Pipeline Completa') {
            steps {
                echo 'Iniciando o script de automacao...'
                // O Jenkins agora entrará no diretório do projeto antes de rodar o script
                dir('getting-started') {
                    sh './pipeline.sh'
                }
            }
        }
    }
}