apiVersion: v1
kind: Service
metadata:
  name: getting-started-service-prd
  namespace: prd
spec:
  selector:
    app: getting-started
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # Usamos um LoadBalancer para expor a aplicação externamente