/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_acme_JniWrapper */

#ifndef _Included_org_acme_JniWrapper
#define _Included_org_acme_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_acme_JniWrapper
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_acme_JniWrapper_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
