####
# Before building the docker image run:
#
# ./gradlew buildNative --docker-build=true
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile -t quarkus/getting-started-gradle .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/getting-started-gradle
#
###
FROM registry.fedoraproject.org/fedora-minimal
WORKDIR /work/
COPY build/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]